### ISSUE TITLE
AttributeError: module 'chumpy.ch' has no attribute 'tensordot'

### ISSUE THREAD

**Issue by neonb88** [polmorenoc/opendr#6]
Hi, I've tried a few things, but it does seem, unfortunately, that the issue is somewhere in your chumpy installation.

Here is my stacktrace:

`python3`

Python 3.6.8 |Anaconda, Inc.| (default, Dec 30 2018, 01:22:34) 
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import chumpy
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/n/anaconda3/envs/cat4/lib/python3.6/site-packages/chumpy/__init__.py", line 2, in <module>
    from chumpy.ch import *
AttributeError: module 'chumpy.ch' has no attribute 'tensordot'
>>> 

And here is more system info:

**Operating System:**
Ubuntu 16.04

output of `uname -a`:
Linux elon-eats-my-shorts 4.15.0-46-generic #49~16.04.1-Ubuntu SMP Tue Feb 12 17:45:24 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

I am using a conda environment, which may be causing part of the problem.

output of `conda list`:
absl-py                   0.7.0                    pypi_0    pypi
astor                     0.7.1                    pypi_0    pypi
blas                      1.0                         mkl  
bzip2                     1.0.6                h14c3975_5  
ca-certificates           2019.1.23                     0  
cairo                     1.14.12              h8948797_3  
certifi                   2018.11.29               py36_0  
chumpy                    0.66                     pypi_0    pypi
cloudpickle               0.8.0                    py36_0    anaconda
cycler                    0.10.0                   py36_0  
cython                    0.29.6                   pypi_0    pypi
cytoolz                   0.9.0.1          py36h14c3975_1    anaconda
dask-core                 1.1.2                      py_0    anaconda
dbus                      1.13.6               h746ee38_0  
decorator                 4.3.2                    py36_0    anaconda
expat                     2.2.6                he6710b0_0  
fastcache                 1.0.2            py36h14c3975_2  
ffmpeg                    4.0                  hcdf2ecd_0  
fontconfig                2.13.0               h9420a91_0  
freeglut                  3.0.0                hf484d3e_5  
freetype                  2.9.1                h8a8886c_1  
gast                      0.2.2                    pypi_0    pypi
glfw                      1.7.1                    pypi_0    pypi
glib                      2.56.2               hd408876_0  
gmp                       6.1.2                h6c8ec71_1  
gmpy2                     2.0.8            py36h10f8cd9_2  
graphite2                 1.3.13               h23475e2_0  
grpcio                    1.19.0                   pypi_0    pypi
gst-plugins-base          1.14.0               hbbd80ab_1  
gstreamer                 1.14.0               hb453b48_1  
h5py                      2.9.0                    pypi_0    pypi
harfbuzz                  1.8.8                hffaf4a1_0  
hdf5                      1.10.2               hba1933b_1  
icu                       58.2                 h9c2bf20_1  
imageio                   2.5.0                    py36_0    anaconda
intel-openmp              2019.1                      144  
jasper                    2.0.14               h07fcdf6_1  
jpeg                      9b                   h024ee3a_2  
keras-applications        1.0.7                    pypi_0    pypi
keras-preprocessing       1.0.9                    pypi_0    pypi
kiwisolver                1.0.1            py36hf484d3e_0  
libedit                   3.1.20181209         hc058e9b_0  
libffi                    3.2.1                hd88cf55_4  
libgcc-ng                 8.2.0                hdf63c60_1  
libgfortran-ng            7.3.0                hdf63c60_0  
libglu                    9.0.0                hf484d3e_1  
libopencv                 3.4.2                hb342d67_1  
libopus                   1.3                  h7b6447c_0  
libpng                    1.6.36               hbc83047_0  
libstdcxx-ng              8.2.0                hdf63c60_1  
libtiff                   4.0.10               h2733197_2  
libuuid                   1.0.3                h1bed415_2  
libvpx                    1.7.0                h439df22_0  
libxcb                    1.13                 h1bed415_1  
libxml2                   2.9.9                he19cac6_0  
markdown                  3.0.1                    pypi_0    pypi
matplotlib                2.2.3            py36hb69df0a_0  
mkl                       2019.1                      144  
mkl_fft                   1.0.10           py36ha843d7b_0  
mkl_random                1.0.2            py36hd81dba3_0  
mpc                       1.1.0                h10f8cd9_1  
mpfr                      4.0.1                hdf1c602_3  
mpmath                    1.1.0                    py36_0  
ncurses                   6.1                  he6710b0_1  
networkx                  2.2                      py36_1    anaconda
numpy                     1.16.2                   pypi_0    pypi
numpy-base                1.16.2           py36hde5b4d6_0  
olefile                   0.46                     py36_0    anaconda
opencv                    3.4.2            py36h6fd60c2_1  
opendr                    0.73                     pypi_0    pypi
openssl                   1.1.1b               h7b6447c_0  
pcre                      8.42                 h439df22_0  
pillow                    5.4.1            py36h34e0f95_0    anaconda
pip                       9.0.0                    pypi_0    pypi
pixman                    0.36.0               h7b6447c_0  
protobuf                  3.7.0                    pypi_0    pypi
py-opencv                 3.4.2            py36hb342d67_1  
pyopengl                  3.1.0                    pypi_0    pypi
pyopengl-accelerate       3.1.0                    pypi_0    pypi
pyparsing                 2.3.1                    py36_0  
pyqt                      5.9.2            py36h05f1152_2  
python                    3.6.8                h0371630_0  
python-dateutil           2.8.0                    py36_0  
pytz                      2018.9                   py36_0  
pywavelets                1.0.1            py36hdd07704_0    anaconda
qt                        5.9.7                h5867ecd_1  
readline                  7.0                  h7b6447c_5  
scikit-image              0.14.2                   pypi_0    pypi
scipy                     1.2.1            py36h7c811a0_0    anaconda
setuptools                40.8.0                   pypi_0    pypi
sip                       4.19.8           py36hf484d3e_0  
six                       1.12.0                   pypi_0    pypi
sqlite                    3.26.0               h7b6447c_0  
sympy                     1.3                      py36_0  
tensorboard               1.12.2                   pypi_0    pypi
tensorflow                1.12.0                   pypi_0    pypi
termcolor                 1.1.0                    pypi_0    pypi
tk                        8.6.8                hbc83047_0  
toolz                     0.9.0                    py36_0    anaconda
tornado                   5.1.1            py36h7b6447c_0  
werkzeug                  0.14.1                   pypi_0    pypi
wheel                     0.33.1                   pypi_0    pypi
xz                        5.2.4                h14c3975_4  
zlib                      1.2.11               h7b6447c_3  
zstd                      1.3.7                h0b5b093_0  

output of `pip freeze`:
absl-py==0.7.0
astor==0.7.1
certifi==2018.11.29
chumpy==0.66
cloudpickle==0.8.0
cycler==0.10.0
Cython==0.29.6
cytoolz==0.9.0.1
dask==1.1.2
decorator==4.3.2
fastcache==1.0.2
gast==0.2.2
glfw==1.7.1
gmpy2==2.0.8
grpcio==1.19.0
h5py==2.9.0
imageio==2.5.0
Keras-Applications==1.0.7
Keras-Preprocessing==1.0.9
kiwisolver==1.0.1
Markdown==3.0.1
matplotlib==2.2.3
mkl-fft==1.0.10
mkl-random==1.0.2
mpmath==1.1.0
networkx==2.2
numpy==1.16.2
olefile==0.46
opendr==0.73
Pillow==5.4.1
protobuf==3.7.0
PyOpenGL==3.1.0
PyOpenGL-accelerate==3.1.0
pyparsing==2.3.1
python-dateutil==2.8.0
pytz==2018.9
PyWavelets==1.0.1
scikit-image==0.14.2
scipy==1.2.1
six==1.12.0
sympy==1.3
tensorboard==1.12.2
tensorflow==1.12.0
termcolor==1.1.0
toolz==0.9.0
tornado==5.1.1
Werkzeug==0.14.1

If I can provide any further information, please let me know.  Thank you for your time :)

**Comment by lucasc896** [comment]
Same issue here - upvoted

**Comment by Dawars** [comment]
Same issue, might be connected to this https://github.com/mattloper/chumpy/pull/25

**Comment by spenceryue** [comment]
I was able to fix this by removing `'tensordot'` from [line 1024](https://github.com/polmorenoc/opendr/blob/1148477e31630edaa247c15be1f02cc4f3f54da0/chumpy/ch.py#L1024) and inserting `__all__.append('tensordot')` at [line 2550](https://github.com/polmorenoc/opendr/blob/1148477e31630edaa247c15be1f02cc4f3f54da0/chumpy/ch.py#L2550) (similar to [what is done for `'tensorinv'`](https://github.com/polmorenoc/opendr/blob/1148477e31630edaa247c15be1f02cc4f3f54da0/chumpy/ch.py#L2033)) in `chumpy/ch.py`.

**Comment by lucasjinreal** [comment]
Please update this change to main repo....... eveyone gets this error

**Comment by raj-gupta1** [comment]
Still getting this error.
AttributeError: 'module' object has no attribute 'tensordot'
System: Windows 10, conda environment, python 2.7, opendr==0.73,chumpy==0.70

**Comment by RK-GOML** [comment]
I yet face same error
